# # .pre-commit-config.yaml

# # Optional: Minimum pre-commit version required
# # minimum_pre_commit_version: 2.9.0

# repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.5.0 # Use the latest stable tag
#     hooks:
#     -   id: check-yaml
#         args: [--allow-multiple-documents]
#     -   id: check-json
#     -   id: check-toml
#     -   id: end-of-file-fixer
#     -   id: trailing-whitespace
#     -   id: check-added-large-files

# -   repo: https://github.com/psf/black
#     rev: 24.3.0 # Use the latest stable version for Black
#     hooks:
#     -   id: black
#         language_version: python3.10 # Specify your Python version

# -   repo: https://github.com/pycqa/flake8
#     rev: 7.0.0 # Use the latest stable version for Flake8
#     hooks:
#     -   id: flake8
#         additional_dependencies: [flake8-bugbear] # Example of adding Flake8 plugins
