# docker-compose.backup.yml (Improved filename format)

version: '3.8'
name: checkpoint-backup

# Reference the network created by the main docker-compose.yml (or manually)
# It MUST be marked external here.
networks:
  shared-db-network:
    external: true
    name: shared-db-network # Must match the actual Docker network name

services:
  postgres-backup:
    image: postgres:13 # Use same major version as your DB
    container_name: postgres_backup_job
    environment:
      # Ensure these match the running postgres container's environment
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Used by pg_dump via PGPASSWORD
      POSTGRES_DB: ${POSTGRES_DB}             # Used in pg_dump command and filename
      POSTGRES_HOST: postgres                # Service name from main compose file
    volumes:
      # Mount local host directory ./db_backups into container's /backups
      - ./db_backups:/backups
    networks:
      # Connect this container to the shared network
      - shared-db-network
    # Updated command to format the filename as YYYYMMDD-databasename.dump
    command: >
      sh -c "pg_dump -h $$POSTGRES_HOST -U $$POSTGRES_USER -d $$POSTGRES_DB -Fc -f /backups/$$(date +%Y%m%d)-$$POSTGRES_DB.dump"