name: db-services

x-postgres-common:
  &postgres-common
  image: postgres:13
  user: "${POSTGRES_TARGET_UID}:${POSTGRES_TARGET_GID}" 
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_HOST: postgres 
    PGPASSWORD: ${POSTGRES_PASSWORD}
  env_file:
    - .env
  volumes:
    - ${POSTGRES_SERVICE_DIR}/backups:${POSTGRES_CONT_DIR}/backups:rw 
  networks:
    - shared-db-network

services:
  postgres-backup:
    <<: *postgres-common
    command:
      - "sh"
      - "-c"
      - > 
        pg_dump -h $$POSTGRES_HOST -U $$POSTGRES_USER -d $$POSTGRES_DB -Fc 
        -f $$POSTGRES_CONT_DIR/backups/$$(date +%Y%m%d)-$$POSTGRES_DB.dump
  
  postgres-cli:
    <<: *postgres-common
    profiles:
      - debug
    user: root
    restart: no
    tty: true
    depends_on:
      postgres-backup:
        condition: service_completed_successfully

networks:
  shared-db-network:
    external: true
    name: shared-db-network