name: dagster-instance-stg

# Common configuration
x-dagster-common: &dagster-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env

services:

  dagster-dagit:
    <<: *dagster-common
    ports:
      - 3000:3000

  dagster-daemon:
    <<: *dagster-common
    command: "dagster-daemon run"
    environment:
      - PGPASS=${PGPASS}
      - PGUID=${PGUID}

  dagster-postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${PGPASS}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - dagster-postgres:/var/lib/postgresql/data

volumes:
  dagster-postgres:
    driver: local
