# IMPORTANT: For testing dbt before moving to docker compose airflow with dbt
# Check the configuration path.

name: dbt-instance
x-common-config:
  &dbt-common-config
  build: 
    context: .
    dockerfile: Dockerfile.dbt
  volumes:
    - ./dbt_project.yml:/usr/app/dbt_project.yml
    - ./dbt:/usr/app/dbt
    - ./data:/usr/app/data
  env_file:
    - .env

services:
  ui:
    <<: *dbt-common-config
    tty: true
    entrypoint: /bin/sh
    command: -c "dbt deps && dbt docs generate && dbt docs serve --port 8080 --host 0.0.0.0"
    ports:
      - "${PORT_DBT_UI:-8888}:8080"
  
  # run:
  #   <<: *dbt-common-config
  #   command: ["run"]
  #   restart: no
  
  # test:
  #   <<: *dbt-common-config
  #   command: ["test"]
  #   restart: no