name: backup

services:
  postgres-backup:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
    volumes:
      - ${AIRFLOW_SERVICE_DIR}/backups:/backups
    networks:
      - shared-db-network
    command: >
      sh -c "pg_dump -h $$POSTGRES_HOST -U $$POSTGRES_USER -d $$POSTGRES_DB -Fc -f /backups/$$(date +%Y%m%d)-$$POSTGRES_DB.dump"
    env_file:
      - .env


networks:
  shared-db-network:
    external: true
    name: shared-db-network