name: db-services

x-postgres-common:
  &postgres-common
  image: postgres:13
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_HOST: postgres

    PGPASSWORD: ${POSTGRES_PASSWORD}
  env_file:
    - .env
  volumes:
    - ${AIRFLOW_SERVICE_DIR}/backups:/backups
  networks:
    - shared-db-network

services:
  postgres-backup:
    <<: *postgres-common
    restart: "no"
    command:
      - "sh"
      - "-c"
      - "pg_dump -h $$POSTGRES_HOST -U $$POSTGRES_USER -d $$POSTGRES_DB -Fc -f /backups/$$(date +%Y%m%d)-$$POSTGRES_DB.dump"

  postgres-restore:
    <<: *postgres-common
    # Restores the specified dump file from the /backups directory.
    # Usage: docker compose -f compose.db-service.yml run --rm postgres-restore <backup_filename.dump>
    # e.g.: docker compose -f compose.db-service.yml run --rm postgres-restore 20250426-mydatabase.dump
    command:
      - "sh"
      - "-c"
      - "pg_restore -h $$POSTGRES_HOST -U $$POSTGRES_USER -d $$POSTGRES_DB --clean --if-exists /backups/$$1"
    tty: true

networks:
  shared-db-network:
    external: true
    name: shared-db-network