bigquery-general-profile:
  target: raw

  outputs:
    raw:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_PRF_PRJ') }}"
      dataset: bronze
      threads: 4
      keyfile: /root/.dbt/bq-keyfile.json

    silver:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_PRF_PRJ') }}"
      dataset: silver
      threads: 4
      keyfile: /root/.dbt/bq-keyfile.json

    prd:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_PRF_PRJ') }}"
      dataset: gold
      threads: 4
      keyfile: /root/.dbt/bq-keyfile.json

    marts:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_PRF_PRJ') }}"
      dataset: marts
      threads: 4
      keyfile: /root/.dbt/bq-keyfile.json